version: "3.8"

services:
    devcontainer:
        build:
            context: .
            dockerfile: Dockerfile
        privileged: true
        volumes:
            - ../..:/workspaces:cached
        env_file: devcontainer.env
        network_mode: service:db
        command: sleep infinity

    db:
        image: postgres:latest
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
        env_file: devcontainer.env

volumes:
    postgres-data:
